### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by gnosisgithub** [WSULib/CVreviewTool#2]
No matter the route I take I am encountering database issues.

I can use my standard MYSQL credentials or create a new one and I keep on hitting errors similar to:
You are working on Table 'CVreviewTool3.person' doesn't exist14

Wondering if file locations are all in the correct locations?

**Comment by ghukill** [comment]
Thanks for pointing this out.  The most recent release (0.75 - https://github.com/WSULib/CVreviewTool/releases/tag/v0.75) includes updated directions for creating the MySQL tables required.
